name = "llmkit-proxy"
main = "src/index.ts"
compatibility_date = "2025-02-18"

[observability]
enabled = true

[[kv_namespaces]]
binding = "BUDGET"
id = "f42fdd9a03704ab3be48e45494939847"

[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "f6eef367a5bd4f56be601269118046f5"
