name: OpenSSF Scorecard

on:
  branch_protection_rule:
  schedule:
    - cron: '0 5 * * 1'  # weekly Monday 5am UTC
  push:
    branches: [main]
  workflow_dispatch:

permissions: read-all

jobs:
  analysis:
    name: Scorecard analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      id-token: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false

      - uses: ossf/scorecard-action@05b42c624433fc40578a4c6e070e2b32d68d33f5 # v2.4.1
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

      - uses: github/codeql-action/upload-sarif@45775bd8235c68ba998cffa5171256f094ddf9f8 # v3
        with:
          sarif_file: results.sarif
